name: doc

on:
  push:
    branches: ["main"]

# Prevent doc action on `main` to conflict with each others.
concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doc:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # deploy on gh-pages
      - name: Setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          environment-name: safe
          cache-environment: true
          cache-downloads: true

      - name: Install library
        run: python -m pip install --no-deps .

      - name: Configure git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Deploy the doc
        run: |
          echo "Get the gh-pages branch"
          git fetch origin gh-pages

          echo "Build and deploy the doc on main"
          mike deploy --push --force main

      # TODO(EN): REMOVE THIS PART WHEN PUBLIC
      # also deploy on valdoc
      - name: Fetch Valence Actions
        uses: actions/checkout@v3
        with:
          repository: valence-platform/valence-actions
          ref: latest
          token: ${{ secrets.VALENCE_GITHUB_TOKEN_PLATFORM }}
          path: .github/valence-actions

      - name: Build and deploy the documentation
        uses: ./.github/valence-actions/deploy-valdoc
        with:
          env-name: safe
          env-file: env.yml
          anaconda-token: ${{ secrets.INVIVOAI_ANACONDA_USER_BOT_TOKEN }}
          valdoc-json-key: ${{ secrets.VALDOC_WRITE_JSON_KEY }}
          doc-name: safe