name: test

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        pytorch-version: ["2.0"]


    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: |
      os=${{ matrix.os }}
      - python=${{ matrix.python-version }}
      - pytorch=${{ matrix.pytorch-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          environment-name: my_env
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}
            pytorch=${{ matrix.pytorch-version }}

      - name: Install library
        run: python -m pip install --no-deps .

      - name: Run pytest
        run: pytest

      - name: Run doc building
        run: mkdocs build